var xmlVal =
    '<eng>' +
    '<verb><base>be</base><pw>was/were</pw><pp>been</pp><zh>在、是</zh></verb>'+
    '<verb><base>become</base><pw>became</pw><pp>become</pp><zh>變成</zh></verb>'+
    '<verb><base>begin</base><pw>began</pw><pp>begun</pp><zh>始</zh></verb>'+
    '<verb><base>bend</base><pw>bent</pw><pp>bent</pp><zh>彎曲</zh></verb>'+
    '<verb><base>bite</base><pw>bit</pw><pp>bitten</pp><zh>咬</zh></verb>'+
    '<verb><base>blow</base><pw>blew</pw><pp>blown</pp><zh>吹</zh></verb>'+
    '<verb><base>break</base><pw>broke</pw><pp>broken</pp><zh>裂</zh></verb>'+
    '<verb><base>bring</base><pw>brought</pw><pp>brought</pp><zh>帶來</zh></verb>'+
    '<verb><base>broadcast</base><pw>broadcast</pw><pp>broadcast</pp><zh>傳播</zh></verb>'+
    '<verb><base>build</base><pw>build</pw><pp>build</pp><zh>建</zh></verb>'+
    '<verb><base>buy</base><pw>bought</pw><pp>bought</pp><zh>買</zh></verb>'+
    '<verb><base>catch</base><pw>caught</pw><pp>caught</pp><zh>及、趕</zh></verb>'+
    '<verb><base>choose</base><pw>chose</pw><pp>chosen</pp><zh>選</zh></verb>'+
    '<verb><base>come</base><pw>came</pw><pp>come</pp><zh>來</zh></verb>'+
    '<verb><base>cost</base><pw>cost</pw><pp>cost</pp><zh>耗費</zh></verb>'+
    '<verb><base>cut</base><pw>cut</pw><pp>cut</pp><zh>切、割</zh></verb>'+
    '<verb><base>dig</base><pw>dug</pw><pp>dug</pp><zh>挖</zh></verb>'+
    '<verb><base>do</base><pw>did</pw><pp>done</pp><zh>做</zh></verb>'+
    '<verb><base>draw</base><pw>drew</pw><pp>drawn</pp><zh>塗、畫</zh></verb>'+
    '<verb><base>drink</base><pw>drank</pw><pp>drunk</pp><zh>喝、飲</zh></verb>'+
    '<verb><base>drive</base><pw>drove</pw><pp>driven</pp><zh>驅、駛</zh></verb>'+
    '<verb><base>eat</base><pw>ate</pw><pp>eaten</pp><zh>吃</zh></verb>'+
    '<verb><base>fall</base><pw>fell</pw><pp>fallen</pp><zh>落</zh></verb>'+
    '<verb><base>feed</base><pw>fed</pw><pp>fed</pp><zh>餵</zh></verb>'+
    '<verb><base>feel</base><pw>felt</pw><pp>felt</pp><zh>覺</zh></verb>'+
    '<verb><base>fight</base><pw>fought</pw><pp>fought</pp><zh>爭</zh></verb>'+
    '<verb><base>find</base><pw>found</pw><pp>found</pp><zh>發現</zh></verb>'+
    '<verb><base>fit</base><pw>fit</pw><pp>fit</pp><zh>合</zh></verb>'+
    '<verb><base>fly</base><pw>flew</pw><pp>flown</pp><zh>飛</zh></verb>'+
    '<verb><base>forget</base><pw>forgot</pw><pp>forgotten</pp><zh>忘記</zh></verb>'+
    '<verb><base>forgive</base><pw>forgave</pw><pp>forgiven</pp><zh>原諒</zh></verb>'+
    '<verb><base>freeze</base><pw>froze</pw><pp>frozen</pp><zh>凍</zh></verb>'+
    '<verb><base>get</base><pw>got</pw><pp>gotten/got</pp><zh>得到、變成</zh></verb>'+
    '<verb><base>give</base><pw>gave</pw><pp>given</pp><zh>給、予</zh></verb>'+
    '<verb><base>go</base><pw>went</pw><pp>gone</pp><zh>去</zh></verb>'+
    '<verb><base>grow</base><pw>grew</pw><pp>grown</pp><zh>長</zh></verb>'+
    '<verb><base>hang</base><pw>hung/hanged</pw><pp>hung/hanged</pp><zh>吊、絞</zh></verb>'+
    '<verb><base>have </base><pw>had</pw><pp>had</pp><zh>有</zh></verb>'+
    '<verb><base>hear</base><pw>heard</pw><pp>heard</pp><zh>聽</zh></verb>'+
    '<verb><base>hide</base><pw>hid</pw><pp>hidden</pp><zh>藏</zh></verb>'+
    '<verb><base>hit</base><pw>hit</pw><pp>hit</pp><zh>碰</zh></verb>'+
    '<verb><base>hold</base><pw>held</pw><pp>held</pp><zh>把、持</zh></verb>'+
    '<verb><base>hurt</base><pw>hurt</pw><pp>hurt</pp><zh>傷</zh></verb>'+
    '<verb><base>keep</base><pw>kept</pw><pp>kept</pp><zh>保持</zh></verb>'+
    '<verb><base>know</base><pw>knew</pw><pp>known</pp><zh>知、識</zh></verb>'+
    '<verb><base>lay</base><pw>laid</pw><pp>laid</pp><zh>放下、鋪上</zh></verb>'+
    '<verb><base>lead</base><pw>led</pw><pp>led</pp><zh>引導</zh></verb>'+
    '<verb><base>leave</base><pw>left</pw><pp>left</pp><zh>離、留</zh></verb>'+
    '<verb><base>lead</base><pw>lent</pw><pp>lent</pp><zh>借</zh></verb>'+
    '<verb><base>let</base><pw>let</pw><pp>let</pp><zh>讓</zh></verb>'+
    '<verb><base>lie</base><pw>lay</pw><pp>lain</pp><zh>躺平、呈現</zh></verb>'+
    '<verb><base>light</base><pw>lit</pw><pp>lit</pp><zh>點、照</zh></verb>'+
    '<verb><base>lose</base><pw>lost</pw><pp>lost</pp><zh>失、迷</zh></verb>'+
    '<verb><base>make</base><pw>made</pw><pp>made</pp><zh>使、造</zh></verb>'+
    '<verb><base>mean</base><pw>meant</pw><pp>meant</pp><zh>意</zh></verb>'+
    '<verb><base>meet</base><pw>met</pw><pp>met</pp><zh>遇</zh></verb>'+
    '<verb><base>pay</base><pw>paid</pw><pp>paid</pp><zh>付</zh></verb>'+
    '<verb><base>put</base><pw>put</pw><pp>put</pp><zh>置</zh></verb>'+
    '<verb><base>quit</base><pw>quit</pw><pp>quit</pp><zh>戒、止</zh></verb>'+
    '<verb><base>read</base><pw>read</pw><pp>read</pp><zh>讀</zh></verb>'+
    '<verb><base>ride</base><pw>rode</pw><pp>ridden</pp><zh>騎</zh></verb>'+
    '<verb><base>ring</base><pw>rang</pw><pp>rung</pp><zh>響</zh></verb>'+
    '<verb><base>rise</base><pw>rose</pw><pp>risen</pp><zh>升</zh></verb>'+
    '<verb><base>run</base><pw>ran</pw><pp>run</pp><zh>跑、營</zh></verb>'+
    '<verb><base>say</base><pw>said</pw><pp>said</pp><zh>說、述</zh></verb>'+
    '<verb><base>see</base><pw>saw</pw><pp>seen</pp><zh>見</zh></verb>'+
    '<verb><base>sell</base><pw>sold</pw><pp>sold</pp><zh>賣</zh></verb>'+
    '<verb><base>send</base><pw>sent</pw><pp>sent</pp><zh>送</zh></verb>'+
    '<verb><base>set</base><pw>set</pw><pp>set</pp><zh>設</zh></verb>'+
    '<verb><base>shake</base><pw>shook</pw><pp>shaken</pp><zh>撼、抖</zh></verb>'+
    '<verb><base>shoot</base><pw>shot</pw><pp>shot</pp><zh>射</zh></verb>'+
    '<verb><base>shut</base><pw>shut</pw><pp>shut</pp><zh>關、閉</zh></verb>'+
    '<verb><base>sing</base><pw>sang</pw><pp>sung</pp><zh>唱、吟</zh></verb>'+
    '<verb><base>sit</base><pw>sat</pw><pp>sat</pp><zh>坐</zh></verb>'+
    '<verb><base>sleep</base><pw>slept</pw><pp>slept</pp><zh>睡</zh></verb>'+
    '<verb><base>slide</base><pw>slid</pw><pp>slid</pp><zh>滑</zh></verb>'+
    '<verb><base>speak</base><pw>spoke</pw><pp>spoken</pp><zh>講、談</zh></verb>'+
    '<verb><base>spend</base><pw>spent</pw><pp>spent</pp><zh>花、用</zh></verb>'+
    '<verb><base>spread</base><pw>spread</pw><pp>spread</pp><zh>播、散</zh></verb>'+
    '<verb><base>stand</base><pw>stood</pw><pp>stood</pp><zh>站、支持</zh></verb>'+
    '<verb><base>steal</base><pw>stole</pw><pp>stolen</pp><zh>偷</zh></verb>'+
    '<verb><base>stick</base><pw>stuck</pw><pp>stuck</pp><zh>挺、貼</zh></verb>'+
    '<verb><base>strike</base><pw>struck</pw><pp>struck</pp><zh>擊</zh></verb>'+
    '<verb><base>swear</base><pw>swore</pw><pp>sworn</pp><zh>宣、發(誓)</zh></verb>'+
    '<verb><base>sweep</base><pw>swept</pw><pp>swept</pp><zh>掃、抹</zh></verb>'+
    '<verb><base>swim</base><pw>swam</pw><pp>swum</pp><zh>游</zh></verb>'+
    '<verb><base>take</base><pw>took</pw><pp>taken</pp><zh>取、拿</zh></verb>'+
    '<verb><base>teach</base><pw>taught</pw><pp>taught</pp><zh>教</zh></verb>'+
    '<verb><base>tear</base><pw>tore</pw><pp>torn</pp><zh>撕、扯</zh></verb>'+
    '<verb><base>tell</base><pw>told</pw><pp>told</pp><zh>辯、訴</zh></verb>'+
    '<verb><base>think</base><pw>thought</pw><pp>thought</pp><zh>認為、想</zh></verb>'+
    '<verb><base>throw</base><pw>threw</pw><pp>thrown</pp><zh>扔、拋</zh></verb>'+
    '<verb><base>understand</base><pw>understood</pw><pp>understood</pp><zh>理解</zh></verb>'+
    '<verb><base>upset</base><pw>upset</pw><pp>upset</pp><zh>煩、擾</zh></verb>'+
    '<verb><base>wake</base><pw>woke</pw><pp>woken</pp><zh>醒</zh></verb>'+
    '<verb><base>wear</base><pw>wore</pw><pp>worn</pp><zh>穿</zh></verb>'+
    '<verb><base>win</base><pw>won</pw><pp>won</pp><zh>贏</zh></verb>'+
    '<verb><base>withdraw</base><pw>withdrew</pw><pp>withdrawn</pp><zh>提、抽</zh></verb>'+
    '<verb><base>write</base><pw>wrote</pw><pp>written</pp><zh>寫</zh></verb>'+
    '</eng>';

